
spring:
  profiles:
    active: real
    include: oauth

---
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        path: /

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles: real
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: spottest
    url: jdbc:mysql://spot-test-server.cqoilwygt3h9.ap-northeast-2.rds.amazonaws.com:3306/spot_test_server
    username: spot
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10000
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    password: zmcwzzbyptbcbafq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
    username: team.spot.v2@gmail.com
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        path: /

spring:
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: spottest
    url: jdbc:mysql://spot-test-server.cqoilwygt3h9.ap-northeast-2.rds.amazonaws.com:3306/spot_test_server
    username: spot
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10000
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: zmcwzzbyptbcbafq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
    username: team.spot.v2@gmail.com

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error